# Site settings
title: Murthy Gidugu
description: ' Data Science Entusiasist'
url: ''
baseurl: '/murthy/'
# google_analytics: 'UA-XXXXXX-X'
# disqus_shortname: 'your-disqus-name'

author:
  name: 'Murthy Gidugu'
  email: narayanamurthy.gidugu@gmail.com
  twitter_username: MurthyGidugu
  facebook_username: gidugu murthy
  github_username:  murthy98
  linkedin_username: r-s-s-s-murthy-gidugu-396799160

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

sass:
    sass_dir: _sass
    style: compressed

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

plugins: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
